[pytest]
DJANGO_SETTINGS_MODULE = ticket_system.settings_test
python_files = test_*.py
addopts = -q --strict-markers
filterwarnings =
    ignore::DeprecationWarning
    ignore::FutureWarning
    ignore:No directory at:UserWarning
