# Generated by Django 5.2.11 on 2026-02-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='has_unread_updates',
            field=models.BooleanField(default=False),
        ),
    ]
