# Generated by Django 5.2.11 on 2026-02-21 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_has_unread_updates'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
