# Generated by Django 5.2.17 on 2026-09-30 04:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


SLA_HOURS = {"critical": (1, 4), "high": (4, 24), "medium": (8, 48), "low": (24, 72)}


def backfill_sla(apps, schema_editor):
    """Give pre-existing tickets SLA deadlines computed from their creation time."""
    from datetime import timedelta

    Ticket = apps.get_model("tickets", "Ticket")
    for t in Ticket.objects.filter(resolution_due__isnull=True).iterator():
        first_h, resolve_h = SLA_HOURS.get(t.priority, (8, 48))
        t.first_response_due = t.created_at + timedelta(hours=first_h)
        t.resolution_due = t.created_at + timedelta(hours=resolve_h)
        t.save(update_fields=["first_response_due", "resolution_due"])


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0006_alter_user_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("status_changed", "Status changed"),
                            ("priority_changed", "Priority changed"),
                            ("category_changed", "Category changed"),
                            ("assigned", "Assigned"),
                            ("commented", "Commented"),
                            ("internal_note", "Internal note"),
                            ("escalated", "Escalated"),
                            ("marked_duplicate", "Marked duplicate"),
                        ],
                        max_length=30,
                    ),
                ),
                ("from_value", models.CharField(blank=True, max_length=200)),
                ("to_value", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="ticketcomment",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="ticket",
            name="ai_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("billing", "Billing"),
                    ("technical", "Technical"),
                    ("account", "Account"),
                    ("general", "General"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="ai_priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="ai_source",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="ticket",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicates",
                to="tickets.ticket",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="escalated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="first_response_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="first_response_due",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="resolution_due",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="ticketcomment",
            name="is_internal",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("support_agent", "Support Agent"),
                    ("admin", "Admin"),
                ],
                db_index=True,
                default="customer",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["status", "priority"], name="tickets_tic_status_b256f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["assigned_to", "status"], name="tickets_tic_assigne_e36302_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="tickets_tic_created_80af85_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["resolution_due"], name="tickets_tic_resolut_0948c6_idx"
            ),
        ),
        migrations.AddField(
            model_name="ticketevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticketevent",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="tickets.ticket",
            ),
        ),
        migrations.RunPython(backfill_sla, migrations.RunPython.noop),
    ]
