# Generated by Django 5.2.17 on 2026-09-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0007_sla_ai_audit_trail"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="embedding",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
