# Generated by Django 5.2.17 on 2026-09-30 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0008_ticket_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="csat_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="csat_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="csat_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="specialties",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="ticketevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("status_changed", "Status changed"),
                    ("priority_changed", "Priority changed"),
                    ("category_changed", "Category changed"),
                    ("assigned", "Assigned"),
                    ("commented", "Commented"),
                    ("internal_note", "Internal note"),
                    ("escalated", "Escalated"),
                    ("marked_duplicate", "Marked duplicate"),
                    ("rated", "Rated"),
                ],
                max_length=30,
            ),
        ),
    ]
