# Generated by Django 5.2.17 on 2026-10-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0009_csat_and_specialties"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
